inherit_from: .rubocop_todo.yml

AllCops:
  SuggestExtensions: false
  NewCops: disable
  Exclude:
    - bin/*

Style/StringLiterals:
  Enabled: false

Naming/FileName:
  Enabled: false

Layout/LineLength:
  Max: 180

Metrics/MethodLength:
  Exclude:
    - test/**/*.rb

Metrics/AbcSize:
  Exclude:
    - test/**/*.rb
